### ISSUE TITLE
Selected Values text overflows from the dropdown if many items selected

### ISSUE THREAD

**Issue by Abdul-Hannan12** [TaimoorHassan/multiselect#41]
![image](https://github.com/TaimoorHassan/multiselect/assets/90274554/69d983ae-c215-4dc7-92be-e75370c24689)

**Comment by soufianebenyaala** [comment]
Same here 
is this package is dead or abandoned

**Comment by soufianebenyaala** [comment]
Hey everyone, I have just created a https://github.com/TaimoorHassan/multiselect/pull/42 to address this, it was an easy fix and let's see if @TaimoorHassan  will approve it soon!
I have tried this solution and it works on my end fine.

For now, to keep things going you can point your multiselect dependency to my repository until the PR is merged by the author.

```
multiselect:
    git:
      url: https://github.com/soufianebenyaala/multiselect.git
      ref: master
```

All the best :).
